-- NexTake personalization and publishing metadata.
-- Apply this migration in the shared Supabase project after the existing articles table exists.

ALTER TABLE IF EXISTS public.articles
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS keywords text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS published_at timestamptz,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS articles_slug_unique
  ON public.articles (slug)
  WHERE slug IS NOT NULL;

CREATE INDEX IF NOT EXISTS articles_published_at_idx
  ON public.articles (published_at DESC)
  WHERE status = 'published';

CREATE INDEX IF NOT EXISTS articles_keywords_gin_idx
  ON public.articles USING gin (keywords);

CREATE TABLE IF NOT EXISTS public.visitor_profiles (
  visitor_id text PRIMARY KEY CHECK (char_length(visitor_id) BETWEEN 16 AND 128),
  interests text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reading_history (
  visitor_id text NOT NULL REFERENCES public.visitor_profiles(visitor_id) ON DELETE CASCADE,
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  opened_at timestamptz NOT NULL DEFAULT now(),
  seconds_read integer NOT NULL DEFAULT 0 CHECK (seconds_read BETWEEN 0 AND 3600),
  scroll_depth smallint NOT NULL DEFAULT 0 CHECK (scroll_depth BETWEEN 0 AND 100),
  completed boolean NOT NULL DEFAULT false,
  PRIMARY KEY (visitor_id, article_id)
);

CREATE INDEX IF NOT EXISTS reading_history_recent_idx
  ON public.reading_history (visitor_id, opened_at DESC);

CREATE TABLE IF NOT EXISTS public.article_engagement_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text NOT NULL REFERENCES public.visitor_profiles(visitor_id) ON DELETE CASCADE,
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('open', 'reading', 'complete', 'bookmark', 'share', 'comment')),
  event_value integer NOT NULL DEFAULT 0 CHECK (event_value BETWEEN 0 AND 3600),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS engagement_article_recent_idx
  ON public.article_engagement_events (article_id, created_at DESC);

CREATE INDEX IF NOT EXISTS engagement_visitor_recent_idx
  ON public.article_engagement_events (visitor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.article_bookmarks (
  visitor_id text NOT NULL REFERENCES public.visitor_profiles(visitor_id) ON DELETE CASCADE,
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (visitor_id, article_id)
);

CREATE TABLE IF NOT EXISTS public.article_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  visitor_id text NOT NULL REFERENCES public.visitor_profiles(visitor_id) ON DELETE CASCADE,
  guest_name text NOT NULL CHECK (char_length(guest_name) BETWEEN 1 AND 80),
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS comments_article_recent_idx
  ON public.article_comments (article_id, created_at DESC)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.recommendation_impressions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id text NOT NULL REFERENCES public.visitor_profiles(visitor_id) ON DELETE CASCADE,
  article_id uuid NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
  position smallint NOT NULL CHECK (position > 0),
  source text NOT NULL CHECK (source IN ('personalized', 'exploration', 'popular', 'latest')),
  shown_at timestamptz NOT NULL DEFAULT now(),
  clicked_at timestamptz
);

CREATE INDEX IF NOT EXISTS recommendation_impressions_recent_idx
  ON public.recommendation_impressions (visitor_id, shown_at DESC);

-- RLS is enabled by default for browser access. Public writes must be exposed through
-- server-side RPCs or an authenticated edge function; no service-role key belongs in Vite.
ALTER TABLE public.visitor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_engagement_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.article_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_impressions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.visitor_profiles, public.reading_history, public.article_engagement_events,
  public.article_bookmarks, public.article_comments, public.recommendation_impressions FROM anon;
REVOKE ALL ON public.visitor_profiles, public.reading_history, public.article_engagement_events,
  public.article_bookmarks, public.article_comments, public.recommendation_impressions FROM authenticated;
